AllCops:
  Exclude:
    - test/dummy/db/schema.rb
    - lib/generators/*/templates/*
    - vendor/**/*
  RunRailsCops: true

Metrics/LineLength:
  Max: 180

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
