language: ruby
rvm:
  - 2.2.0
addons:
  code_climate:
    repo_token: aa73795693f24833b2e31001577d1fdbb8bbafef23b0eb6e1e580f1388433564
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5a4fa5f4365fc0a9d2d4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
